### ISSUE TITLE
[@lazy-cjk/japanese] Removes non-japanese characters in romanization

### ISSUE THREAD

**Issue by Bas950** [bluelovers/ws-regexp#2]
run: `romanize("nihao， zhehenku。")`
output: ` .`

run: `romanize("(C)ookieッ")`
output: `'`

run: `romanize("淑力ッ")`
output: `'`

**Comment by bluelovers** [comment]
maybe u want use this 

@lazy-cjk/slugify
https://github.com/bluelovers/ws-regexp/blob/master/packages/%40lazy-cjk/slugify/test/slugify.spec.ts

**Comment by Bas950** [comment]
Fixed by @bluelovers in https://github.com/bluelovers/ws-regexp/commit/869a2c04e48012ee8a2c8800cfacf7e0ef745406

```ts
import { romanize } from '@lazy-cjk/japanese'

romanize(text, { ignoreUnSupported: true })
```
